appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
bot:
  automerge: true
provider:
  win: azure
travis:
  secure:
    BINSTAR_TOKEN: L4TMyeETYBPsAOHadou/Aaisd6JCvLO/PKIHDluvRsZB5vdc0AEZGAjyTaVwk/sy6+G9NnUrhMM/jF7nl1AephblkQzcTYjzyO0STeKnULnMa4PKRyAjdTLAP5idvfTvYErFarBd3nmQShj0xS3eTl99V+p8PdI6R7JYtH878IhG6xsxIzppgO0RM7Wx+rZI4nJSivlnp5rNR8jFVOO4PCStYkk185vQoCfYYyMYt5bd/S8Jol+1+eAjYGB1x2leehUAgOp14/wpaEpxNJSnbfUd3ldJx51lE3AdPKiMzvbhEV/Elqq4QlSBAxVWgdO3Rut0ZVlj0chkeDzMGpWFeavbPlwlV+UppKj9pgm+OKxi8jIkSw9VKIyhKphfKWr2dhb4wbd5XOq2mngANnpnElNoGnOkPzpgjtl/mGs13DoeidzPkLVajb1xwUZDqzeYa2uUJD6yuPDfu2pvyc9ar4+SJGenjlnsI8vL42rGgC5Jx/wT67I5gfbeGxnel5+ucfY2qysCAo+tvRrSOIIiGWf3W7BtkRaeSASzeD3UV9Xu26NnCBNAmeGyjotphOMoBak79Ova+FZ2ihUmxpcXLXBjhkwOzN3aAPfgINlDzwPoE08TR+bWYU2oLwktutwJMhhoU5Hfmy0zJCIzdzF/tFEJS2VAk2u+bRin6Q4Wjnc=
